# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jm <jm@student.42lyon.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/17 20:20:20 by jm                #+#    #+#              #
#    Updated: 2024/08/31 17:59:23 by jm               ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

FROM owasp/modsecurity-crs:4.6-nginx-alpine-202408280908

COPY ./templates/404.html /usr/share/nginx/html/
# COPY ./templates/404.css ${STATICFILES_DIR}

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "nginx", "-g", "daemon off;" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]