# ARG default values are overriden at build time

ARG PYTHON_TAG=3.10.15-alpine3.20

FROM python:${PYTHON_TAG}
# ARG HOST_IP

# ENV HOST_IP=${HOST_IP}

ARG PYTHON_UID=1111
ARG PYTHON_GID=1111
ARG PYTHON_USER=user
ARG PYTHON_SRCS=./srcs
ARG SHARED_GID=1010
ARG PYTHON_HOME=/usr/share/web
ARG PYTHON_DIRS_TO_MAKE=.
ARG STATICFILES_DIR=/usr/share/web/volumes/www/static

USER 0

WORKDIR ${PYTHON_HOME}

RUN --mount=type=bind,source=./tools/requirements.txt,target=./requirements.txt <<EOF
apk add --update --no-cache dumb-init curl shadow vim
useradd --uid ${PYTHON_UID} --user-group -m --no-log-init --home-dir ${PYTHON_HOME} --shell /bin/sh --comment "container's rootless user" ${PYTHON_USER}
addgroup -g ${SHARED_GID} transcendance
addgroup ${PYTHON_USER} transcendance
mkdir -p ${PYTHON_DIRS_TO_MAKE}
chmod 0700 ${PYTHON_HOME} ${PYTHON_HOME}/container-init.d ${PYTHON_HOME}/volumes
chmod 0770 ${STATICFILES_DIR}
chmod 1500 ${PYTHON_HOME}/secrets
chown -R ${PYTHON_UID}:${SHARED_GID} ${PYTHON_HOME}
chown ${PYTHON_UID}:${PYTHON_GID} ${PYTHON_HOME}/secrets
pip install -r ./requirements.txt
pip install django-cors-headers
pip install aiohttp
EOF

COPY --chown=${PYTHON_UID}:${PYTHON_GID} --chmod=770 ./tools/HOST_IP.sh ${PYTHON_HOME}/container-init.d
COPY --chown=${PYTHON_UID}:${PYTHON_GID} --chmod=700 ./tools/script.sh ${PYTHON_HOME}/container-init.d
COPY --chown=${PYTHON_UID}:${PYTHON_GID} --chmod=770 ./${PYTHON_SRCS}/ ${PYTHON_HOME}/apps

WORKDIR ${PYTHON_HOME}/apps

USER ${PYTHON_UID}

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
# CMD [ "{$PYTHON_HOME}/container-init.d/script.sh" ]
CMD [ "sh", "-c", "${PYTHON_HOME}/container-init.d/script.sh" ]

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# ENTRYPOINT [ "tail", "-f", "/dev/null" ]
