# ARG default values are overriden at build time

ARG WEB_TAG=3.10.15-alpine3.20

FROM python:${WEB_TAG}
# ARG HOST_IP

# ENV HOST_IP=${HOST_IP}

ARG WEB_UID=1111
ARG WEB_GID=1111
ARG SHARED_GID=1010
ARG WEB_HOME=/usr/share/web
ARG WEB_DIRS_TO_MAKE=.
ARG STATICFILES_DIR=/usr/share/web/volumes/www/static

USER 0

WORKDIR ${WEB_HOME}

RUN --mount=type=bind,source=./tools/requirements.txt,target=./requirements.txt <<EOF
apk add --update --no-cache dumb-init curl shadow
useradd --uid ${WEB_UID} --user-group -m --no-log-init --home-dir ${WEB_HOME} --shell /bin/sh --comment "container's rootless user" web
addgroup -g ${SHARED_GID} transcendance
addgroup web transcendance
mkdir -p ${WEB_DIRS_TO_MAKE}
chmod 0700 ${WEB_HOME} ${WEB_HOME}/container-init.d ${WEB_HOME}/volumes
chmod 0770 ${STATICFILES_DIR}
chmod 1500 ${WEB_HOME}/secrets
chown -R ${WEB_UID}:${SHARED_GID} ${WEB_HOME}
chown ${WEB_UID}:${WEB_GID} ${WEB_HOME}/secrets
pip install -r ./requirements.txt
pip install django-cors-headers
EOF

COPY --chown=${WEB_UID}:${WEB_GID} --chmod=700 ./tools/script.sh ${WEB_HOME}/container-init.d
COPY --chown=${WEB_UID}:${WEB_GID} --chmod=770 ./srcs/ ${WEB_HOME}/apps
COPY --chown=${WEB_UID}:${WEB_GID} --chmod=770 ./tools/HOST_IP.sh ${WEB_HOME}/container-init.d

WORKDIR ${WEB_HOME}/apps

USER ${WEB_UID}

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "/usr/share/web/container-init.d/script.sh" ]

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# ENTRYPOINT [ "tail", "-f", "/dev/null" ]
