# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jm <jm@student.42lyon.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/17 20:20:20 by jm                #+#    #+#              #
#    Updated: 2024/07/19 20:36:32 by jm               ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

FROM nginx:alpine

RUN mkdir -p /etc/container-init.d

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]