# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jm <jm@student.42lyon.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/17 20:20:20 by jm                #+#    #+#              #
#    Updated: 2024/07/23 21:29:26 by jm               ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

ARG STATICFILES_DIR

FROM nginx:alpine

RUN mkdir -p /etc/container-init.d ${STATICFILES_DIR}

COPY ./templates/404.html /usr/share/nginx/html/
COPY ./templates/404.css ${STATICFILES_DIR}

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]