# ARG default values are overriden at build time

ARG PYTHON_TAG=3.10.15-alpine3.20

FROM python:${PYTHON_TAG}

ARG PYTHON_UID=xxxx
ARG PYTHON_GID=xxxx
ARG PYTHON_USER=xxxx
ARG PYTHON_SRCS=.
ARG SHARED_GID=1010
ARG PYTHON_HOME=/usr/share/xxx
ARG PYTHON_DIRS_TO_MAKE=.
ARG STATICFILES_DIR=.
ARG PYTHON_MEDIA_DIR=.
ARG SCRIPT_SH=script.sh

USER 0

WORKDIR ${PYTHON_HOME}

RUN --mount=type=bind,source=./tools/requirements.txt,target=./requirements.txt <<EOF
apk add --update --no-cache dumb-init curl shadow
useradd --uid ${PYTHON_UID} --user-group -m --no-log-init --home-dir ${PYTHON_HOME} --shell /bin/sh --comment "container's rootless user" ${PYTHON_USER}
addgroup -g ${SHARED_GID} transcendance
addgroup ${PYTHON_USER} transcendance
mkdir -p ${PYTHON_DIRS_TO_MAKE}
chmod 0700 ${PYTHON_HOME} ${PYTHON_HOME}/container-init.d ${PYTHON_HOME}/volumes
chmod 0770 ${STATICFILES_DIR}
chmod 1500 ${PYTHON_HOME}/secrets
chown -R ${PYTHON_UID}:${SHARED_GID} ${PYTHON_HOME}
chown ${PYTHON_UID}:${PYTHON_GID} ${PYTHON_HOME}/secrets
pip install -r ./requirements.txt
EOF

COPY --chown=${PYTHON_UID}:${PYTHON_GID} --chmod=770 ./tools/HOST_IP.sh ${PYTHON_HOME}/container-init.d
COPY --chown=${PYTHON_UID}:${PYTHON_GID} --chmod=700 ./${SCRIPT_SH} ${PYTHON_HOME}/container-init.d
COPY --chown=${PYTHON_UID}:${PYTHON_GID} --chmod=770 ./${PYTHON_SRCS}/ ${PYTHON_HOME}/apps
COPY --chown=${PYTHON_UID}:${PYTHON_GID} --chmod=770 ./media/ ${PYTHON_MEDIA_DIR}/

WORKDIR ${PYTHON_HOME}/apps

USER ${PYTHON_UID}

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "sh", "-c", "${PYTHON_HOME}/container-init.d/script.sh" ]

# ENTRYPOINT [ "tail", "-f", "/dev/null" ]