# NB: ARG default values are overriden at build time

ARG VAULT_VERSION=1.17.3

FROM hashicorp/vault:${VAULT_VERSION}

ARG VAULT_UID=100
ARG VAULT_GID=1000
ARG SHARED_GID=1010
ARG VAULT_HOME=/vault
ARG VAULT_INIT_DIRS_TO_MAKE=.

USER 0

WORKDIR ${VAULT_HOME}

RUN <<EOF
addgroup -g ${SHARED_GID} transcendance
addgroup vault transcendance
apk add --update --no-cache curl jq openssl
mkdir -p ${VAULT_INIT_DIRS_TO_MAKE}
chmod 700 ${VAULT_HOME} ${VAULT_HOME}/container-init.d
chown -R ${VAULT_UID}:${SHARED_GID} ${VAULT_HOME}
EOF

COPY --chown=${VAULT_UID}:${VAULT_GID} --chmod=500 ./tools/script.sh ./container-init.d/script.sh
COPY --chown=${VAULT_UID}:${VAULT_GID} --chmod=500 ./tools/create-root-ca.sh ./container-init.d/create-root-ca.sh
COPY --chown=${VAULT_UID}:${VAULT_GID} --chmod=500 ./tools/generate-nginx-ssl-certs.sh ./container-init.d/generate-nginx-ssl-certs.sh
COPY --chown=${VAULT_UID}:${VAULT_GID} --chmod=500 ./tools/generate-web-ssl-certs.sh ./container-init.d/generate-web-ssl-certs.sh
COPY --chown=${VAULT_UID}:${VAULT_GID} --chmod=500 ./tools/vault-ssl.sh ./container-init.d/vault-ssl.sh
COPY --chown=${VAULT_UID}:${VAULT_GID} --chmod=500 ./conf/vault-ssl.cnf ./container-init.d/vault-ssl.cnf

USER ${VAULT_UID}

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD [ "/bin/sh", "./container-init.d/script.sh" ]
# ENTRYPOINT ["docker-entrypoint.sh"]
# CMD ["server" "-dev"]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]