# Generated by Django 5.0.6 on 2024-08-06 11:22

import authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.pnj', null=True, upload_to='photos/', validators=[authentification.models.validate_image_extension]),
        ),
    ]
