# Generated by Django 5.0.6 on 2024-09-05 12:49

import authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='../static/photos/default.png', null=True, upload_to='../static/photos/', validators=[authentification.models.validate_image_extension]),
        ),
    ]
