# NB: ARG default values are overriden at build time

ARG POSTGRES_TAG=12.20-alpine3.20

FROM postgres:${POSTGRES_TAG}

ARG POSTGRES_UID=70
ARG POSTGRES_GID=70
ARG SHARED_GID=1010
ARG POSTGRES_HOME=/usr/share/postgres
ARG POSTGRES_DIRS_TO_MAKE=.

USER 0

WORKDIR ${POSTGRES_HOME}

RUN <<EOF
addgroup -g ${SHARED_GID} transcendance
addgroup postgres transcendance
apk add --update --no-cache dumb-init curl jq envsubst
mkdir -p ${POSTGRES_DIRS_TO_MAKE}
chmod 0700 ${POSTGRES_HOME} ${POSTGRES_HOME}/container-init.d ${POSTGRES_HOME}/volumes
chmod 1500 ${POSTGRES_HOME}/secrets
chown -R ${POSTGRES_UID}:${SHARED_GID} ${POSTGRES_HOME}
chown ${POSTGRES_UID}:${POSTGRES_GID} ${POSTGRES_HOME}/secrets /usr/local/share/postgresql/postgresql.conf.sample
EOF

COPY --chown=${POSTGRES_UID}:${POSTGRES_GID} --chmod=700 ./tools/script.sh ${POSTGRES_HOME}/container-init.d/
COPY --chown=${POSTGRES_UID}:${POSTGRES_GID} --chmod=644 ./conf/pg_hba.conf /usr/local/share/postgresql/pg_hba.conf.sample
COPY --chown=${POSTGRES_UID}:${POSTGRES_GID} --chmod=644 ./conf/postgresql.conf /usr/local/share/postgresql/postgresql.conf.sample.template

USER ${POSTGRES_UID}

ENTRYPOINT [ "dumb-init", "--" ]
CMD [ "/usr/share/postgres/container-init.d/script.sh" ]
# ENTRYPOINT [ "docker-entrypoint.sh", "postgres" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]