
FROM postgres:alpine

WORKDIR /usr/src/apps

RUN apk add --update --no-cache curl jq
RUN mkdir -p /etc/container-init.d

COPY --chown=root:root --chmod=700 ./tools/script.sh /etc/container-init.d

COPY --chmod=644 ./conf/pg_hba.conf /usr/local/share/postgresql/pg_hba.conf.sample
COPY --chmod=644 ./conf/postgresql.conf /usr/local/share/postgresql/postgresql.conf.sample
# COPY --chmod=644 ./conf/init.sql /docker-entrypoint-initdb.d

CMD [ "/etc/container-init.d/script.sh" ]

# ENTRYPOINT [ "docker-entrypoint.sh", "postgres" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]