
services:
  setup:
    image: ${SETUP_IMAGE}
    container_name: ${SETUP_CONTAINER}
    build:
      context: ./requirements/elk/setup/
      args:
        - STACK_VERSION=${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD_FILE=${ELASTIC_PASSWORD_LOCALFILE}
      - ELASTICSEARCH_HOSTXPORT=${ELASTICSEARCH_HOSTXPORT}
      - KIBANA_USER=${KIBANA_USER}
      - KIBANA_PASSWORD_FILE=${KIBANA_PASSWORD_LOCALFILE}
      - LOGSTASH_ES_USER=${LOGSTASH_ES_USER}
      - LOGSTASH_ES_USERFULLNAME=${LOGSTASH_ES_USERFULLNAME}
      - LOGSTASH_ES_USER_PASSWORD_FILE=${LOGSTASH_ES_USER_PASSWORD_LOCALFILE}
      - LOGSTASH_ES_ROLE=${LOGSTASH_ES_ROLE}
    secrets:
      - es_passwd_file
      - kibana_passwd_file
      - logstash_es_user_passwd_file
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/elasticsearch/elasticsearch.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  elasticsearch:
    # depends_on:
    #   - setup
    depends_on:
      setup:
        condition: service_healthy
    image: ${ES_IMAGE}
    container_name: ${ES_CONTAINER}
    build:
      context: ./requirements/elk/elasticsearch/
      args:
        - STACK_VERSION=${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - ./requirements/elk/elasticsearch/conf/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - eslogs:${ES_LOGS_VOLUME_PATH}
      - esdata:/usr/share/elasticsearch/data
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    environment:
      - discovery.type=single-node
      - cluster.name=${CLUSTER_NAME}
      - ELASTIC_PASSWORD_FILE=${ELASTIC_PASSWORD_LOCALFILE}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
    secrets:
      - es_passwd_file
      - kibana_passwd_file
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt ${ELASTICSEARCH_HOSTXPORT} | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    # depends_on:
    #   - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: ${KIBANA_IMAGE}
    container_name: ${KIBANA_CONTAINER}
    build: 
      context: ./requirements/elk/kibana/
      args:
        - STACK_VERSION=${STACK_VERSION}
    volumes:
      - ./requirements/elk/kibana/conf/kibana-docker:/usr/local/bin/kibana-docker
      - certs:/usr/share/kibana/config/certs
      # - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:${KIBANA_PORT}
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTXPORT}
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD_FILE=${KIBANA_PASSWORD_LOCALFILE}
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - TELEMETRY_ENABLED=false
    secrets:
      - kibana_passwd_file
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  logstash:
    # depends_on:
    #   - elasticsearch
    depends_on:
      kibana:
        condition: service_healthy
    image: ${LOGSTASH_IMAGE}
    container_name: ${LOGSTASH_CONTAINER}
    user: "0"
    build: 
      context: ./requirements/elk/logstash/
      args:
        - STACK_VERSION=${STACK_VERSION}
    volumes:
      - ./requirements/elk/logstash/conf/docker-entrypoint:/usr/local/bin/docker-entrypoint
      - ./requirements/elk/logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./requirements/elk/logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./test.log:/tmp/test.log
      - certs:/usr/share/logstash/config/certs
      - eslogs:${ES_LOGS_VOLUME}
      # - logstashdata:/usr/share/logstash/data
    expose:
      - ${LOGSTASH_PORT}
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD_FILE=${ELASTIC_PASSWORD_LOCALFILE}
      - ELASTICSEARCH_HOSTXPORT=${ELASTICSEARCH_HOSTXPORT}
      - LOGSTASH_KEYSTORE_PASS_FILE=${LOGSTASH_KEYSTORE_PASS_LOCALFILE}
      - LOGSTASH_ES_USER=${LOGSTASH_ES_USER}
      - LOGSTASH_ES_USER_PASSWORD_FILE=${LOGSTASH_ES_USER_PASSWORD_LOCALFILE}
      - LOGSTASH_ES_CA=${LOGSTASH_ES_CA}
      - LS_JAVA_OPTS=-Xmx512m -Xms512m -Dlog4j2.formatMsgNoLookups=true
      - xpack.monitoring.elasticsearch.hosts=${ELASTICSEARCH_HOSTXPORT}
    secrets:
      - es_passwd_file
      - logstash_keystore_pass_file
      - logstash_es_user_passwd_file
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:${LOGSTASH_PORT} | grep -q 'HTTP/1.1'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  elkready:
    # depends_on:
    #   - logstash
    depends_on:
      logstash:
        condition: service_healthy
    image: alpine
    container_name: elkready_c
    command: echo "elk stack is ready"

volumes:
  certs:
    driver: local
  esdata:
    driver: local
  eslogs:
    driver: local
  kibanadata:
    driver: local

secrets:
  es_passwd_file:
    file: ${ELASTIC_PASSWORD_HOSTFILE}
  kibana_passwd_file:
    file: ${KIBANA_PASSWORD_HOSTFILE}
  logstash_keystore_pass_file:
    file: ${LOGSTASH_KEYSTORE_PASS_HOSTFILE}
  logstash_es_user_passwd_file:
    file: ${LOGSTASH_ES_USER_PASSWORD_HOSTFILE}
