# Generated by Django 4.2.3 on 2024-10-29 12:18

import authentification.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_customuser_friend_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/', validators=[authentification.models.validate_image_extension]),
        ),
    ]
