
ARG ALPINE_VERSION

FROM alpine:${ALPINE_VERSION}

RUN apk add --update --no-cache curl openssl
RUN mkdir -p /etc/container-init.d

COPY --chmod=500 ./tools/script.sh /etc/container-init.d/script.sh
COPY --chmod=500 ./conf/vault_ssl.cnf /vault/vault_ssl.cnf

ENTRYPOINT [ "/etc/container-init.d/script.sh" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]