# ARG default values are overriden at build time

ARG VAULT_VERSION=1.17.3

FROM hashicorp/vault:${VAULT_VERSION}

ARG VAULT_UID=100
ARG VAULT_GID=1000
ARG SHARED_GID=1010
ARG VAULT_HOME=/vault
ARG VAULT_DIRS_TO_MAKE=.

USER 0

WORKDIR ${VAULT_HOME}

RUN <<EOF
addgroup -g ${SHARED_GID} transcendance
addgroup vault transcendance
apk add --update --no-cache curl openssl envsubst
mkdir -p ${VAULT_DIRS_TO_MAKE}
chmod 700 ${VAULT_HOME} ${VAULT_HOME}/healthiness ${VAULT_HOME}/container-init.d
chown -R ${VAULT_UID}:${SHARED_GID} ${VAULT_HOME}
EOF

COPY --chown=${VAULT_UID}:${VAULT_GID} --chmod=500 ./conf/vault.hcl ${VAULT_HOME}/config/vault.hcl.template
COPY --chown=${VAULT_UID}:${VAULT_GID} --chmod=500 ./tools/script.sh ${VAULT_HOME}/container-init.d/

USER ${VAULT_UID}

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "sh", "-c", "${VAULT_HOME}/container-init.d/script.sh" ]