# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jm <jm@student.42lyon.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/17 20:20:20 by jm                #+#    #+#              #
#    Updated: 2024/08/16 21:11:28 by jm               ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

ARG VAULT_VERSION

FROM hashicorp/vault:${VAULT_VERSION}

# USER "0"

RUN apk add --no-cache curl
RUN mkdir -p /etc/container-init.d

COPY --chmod=500 ./tools/script.sh /etc/container-init.d/script.sh
# COPY --chmod=500 ./conf/payload.json payload.json

CMD [ "/etc/container-init.d/script.sh" ]
# ENTRYPOINT ["docker-entrypoint.sh"]
# CMD ["server" "-dev"]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]