
ARG STACK_VERSION=8.14.1

FROM logstash:${STACK_VERSION}

ARG LOGSTASH_DIRS_TO_MAKE=.

USER 0

RUN <<EOF
mkdir -p ${LOGSTASH_DIRS_TO_MAKE}
chown -R 1000:1000 /usr/share/logstash
find /usr/share/logstash -maxdepth 1 -type d -exec chmod 00750 \{\} \;
find /usr/share/logstash -maxdepth 1 -type f -exec chmod o-rwx \{\} \;
EOF
#In '00777' file permission, 00 allows to unset eventual SUID,GUID,STICKY bit privilegies

COPY --chown=1000:1000 --chmod=500 ./tools/script.sh /usr/share/logstash/script.sh
COPY --chown=1000:1000 --chmod=777 ./conf/pipelines.yml			/usr/share/logstash/config/pipelines.yml
COPY --chown=1000:1000 --chmod=777 ./conf/log4j2.properties		/usr/share/logstash/config/log4j2.properties
COPY --chown=1000:1000 --chmod=777 ./conf/my-logstash.yml		/usr/share/logstash/config/my-logstash.yml
COPY --chown=1000:1000 --chmod=777 ./conf/logstash.conf			/usr/share/logstash/pipeline/logstash.conf
COPY --chown=1000:1000 --chmod=777 ./conf/11-logstash.conf		/usr/share/logstash/pipeline1/11-logstash.conf
COPY --chown=1000:1000 --chmod=777 ./conf/12-logstash.conf		/usr/share/logstash/pipeline2/12-logstash.conf
COPY --chown=1000:1000 --chmod=777 ./conf/14-logstash.conf		/usr/share/logstash/pipeline4/14-logstash.conf
# TODO rm
COPY --chown=1000:1000 --chmod=777 ./test.log					/tmp/test.log

USER 1000

# ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]
ENTRYPOINT [ "bash", "/usr/share/logstash/script.sh" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]
