# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jm <jm@student.42lyon.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/17 20:20:20 by jm                #+#    #+#              #
#    Updated: 2024/07/16 21:56:19 by jm               ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

ARG STACK_VERSION

FROM logstash:${STACK_VERSION}


ENTRYPOINT [ "docker-entrypoint" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]