
ARG STACK_VERSION=8.14.1

FROM elasticsearch:${STACK_VERSION}

ARG SHARED_GID=1010

USER 0

RUN <<EOF
apt-get update && apt-get install -y dumb-init
addgroup --gid ${SHARED_GID} transcendance
addgroup elasticsearch transcendance
chown -R 1000:1000 /usr/share/elasticsearch
find /usr/share/elasticsearch -maxdepth 1 -type d -exec chmod 00750 \{\} \;
find /usr/share/elasticsearch -maxdepth 2 -type f -exec chmod o-rwx \{\} \;
EOF

COPY --chown=1000:1000 --chmod=777 ./conf/log4j2.properties /usr/share/elasticsearch/config/log4j2.properties

USER 1000

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "/usr/local/bin/docker-entrypoint.sh", "eswrapper" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]