
ARG STACK_VERSION=8.14.1

FROM elasticsearch:${STACK_VERSION}

USER "0"

RUN mkdir -p /etc/container-init.d

COPY --chown=root:root --chmod=500 ./tools/script.sh /etc/container-init.d/script.sh

ENTRYPOINT [ "/etc/container-init.d/script.sh" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]