# ARG default values are overriden at build time

ARG BACKEND_TAG=3.10.15-alpine3.20

FROM python:${BACKEND_TAG}
# ARG HOST_IP

# ENV HOST_IP=${HOST_IP}

ARG BACKEND_UID=1111
ARG BACKEND_GID=1111
ARG SHARED_GID=1010
ARG BACKEND_HOME=/usr/share/backend
ARG BACKEND_DIRS_TO_MAKE=.
ARG STATICFILES_DIR=/usr/share/backend/volumes/www/static
ARG BACKEND_MEDIA_DIR=/usr/share/backend/volumes/www/media

USER 0

WORKDIR ${BACKEND_HOME}

RUN --mount=type=bind,source=./tools/requirements.txt,target=./requirements.txt <<EOF
apk add --update --no-cache dumb-init curl shadow
useradd --uid ${BACKEND_UID} --user-group -m --no-log-init --home-dir ${BACKEND_HOME} --shell /bin/sh --comment "container's rootless user" backend
addgroup -g ${SHARED_GID} transcendance
addgroup backend transcendance
mkdir -p ${BACKEND_DIRS_TO_MAKE}
chmod 0700 ${BACKEND_HOME} ${BACKEND_HOME}/container-init.d ${BACKEND_HOME}/volumes
chmod 0770 ${STATICFILES_DIR}
chmod 1500 ${BACKEND_HOME}/secrets
chown -R ${BACKEND_UID}:${SHARED_GID} ${BACKEND_HOME}
chown ${BACKEND_UID}:${BACKEND_GID} ${BACKEND_HOME}/secrets
pip install -r ./requirements.txt
pip install django-cors-headers
EOF

# COPY ./srcs/ .
COPY --chown=${BACKEND_UID}:${BACKEND_GID} --chmod=700 ./tools/script.sh ${BACKEND_HOME}/container-init.d
COPY --chown=${BACKEND_UID}:${BACKEND_GID} --chmod=770 ./srcs/ ${BACKEND_HOME}/apps
COPY --chown=${BACKEND_UID}:${BACKEND_GID} --chmod=770 ./media/ ${BACKEND_MEDIA_DIR}/
# COPY --chown=${BACKEND_UID}:${BACKEND_GID} --chmod=770 ./tools/HOST_IP.sh ${BACKEND_HOME}/container-init.d

WORKDIR ${BACKEND_HOME}/apps

USER ${BACKEND_UID}

ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD [ "/usr/share/backend/container-init.d/script.sh" ]

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# ENTRYPOINT [ "tail", "-f", "/dev/null" ]
