
ARG MODSECURITY_TAG

FROM owasp/modsecurity-crs:${MODSECURITY_TAG}

ARG MODSEC_DEBUG_LOG_DIR MODSEC_AUDIT_LOG_DIR NGINX_LOG_FILES

USER root
RUN apk add --update --no-cache jq
RUN mkdir -p ${MODSEC_DEBUG_LOG_DIR} ${MODSEC_AUDIT_LOG_DIR}
RUN touch ${NGINX_LOG_FILES}
RUN chown nginx ${MODSEC_DEBUG_LOG_DIR} ${MODSEC_AUDIT_LOG_DIR} ${NGINX_LOG_FILES}

USER nginx
COPY ./templates/404.html /usr/share/nginx/html/

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "nginx", "-g", "daemon off;" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]