# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jm <jm@student.42lyon.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/17 20:20:20 by jm                #+#    #+#              #
#    Updated: 2024/09/06 17:17:27 by jm               ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

ARG MODSECURITY_TAG

FROM owasp/modsecurity-crs:${MODSECURITY_TAG}

ARG MODSEC_DEBUG_LOG_DIR MODSEC_AUDIT_LOG_DIR NGINX_LOG_FILES

USER root
RUN apk add --update --no-cache jq
RUN mkdir -p ${MODSEC_DEBUG_LOG_DIR} ${MODSEC_AUDIT_LOG_DIR}
RUN touch ${NGINX_LOG_FILES}
RUN chown nginx ${MODSEC_DEBUG_LOG_DIR} ${MODSEC_AUDIT_LOG_DIR} ${NGINX_LOG_FILES}

USER nginx
COPY ./templates/404.html /usr/share/nginx/html/

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "nginx", "-g", "daemon off;" ]
# ENTRYPOINT [ "tail", "-f", "/dev/null" ]